version: 2

jobs:
  build:
    working-directory: ~/sonos_discovery
    docker:
      - image: scorpil/rust:1.18
    steps:
      - checkout
      - run: rustup run nightly cargo run --bin sonos_discovery
