version: 2

jobs:
  build:
    working-directory: ~/sonos_discovery
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - run:
          name: Update nightly version
          command: "rustup update nightly"
      - run:
          name: Show version
          command: "rustup show"
      - run:
          name: Run bin
          command: "rustup run nightly cargo build --bin sonos_discovery"
