version: 2

jobs:
  build:
    working-directory: ~/sonos_discovery
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - run: rustup update nightly
      - run: rustup show
      - run: rustup run nightly cargo run --bin sonos_discovery
